-- Promote `location` from a free-text column on Course/Trainer to a Location
-- table referenced by foreign key.
--
-- Hand-written rather than autogenerated: Prisma's default diff would DROP the
-- existing location columns and lose the data. This migration creates the
-- lookup table, backfills it from the values already in use, rewires both
-- tables to point at it, and only then drops the old columns — so it is safe to
-- run against a populated database.

-- 1. The lookup table.
CREATE TABLE "Location" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Location_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "Location_name_key" ON "Location"("name");

-- 2. Seed it from every location string currently in use, across both tables.
INSERT INTO "Location" ("id", "name", "createdAt", "updatedAt")
SELECT gen_random_uuid()::text, "name", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (
    SELECT DISTINCT "location" AS "name" FROM "Course"
    UNION
    SELECT DISTINCT "location" AS "name" FROM "Trainer"
) AS existing;

-- 3. Course: add the FK column, backfill by name, then enforce NOT NULL.
ALTER TABLE "Course" ADD COLUMN "locationId" TEXT;

UPDATE "Course" c
SET "locationId" = l."id"
FROM "Location" l
WHERE l."name" = c."location";

ALTER TABLE "Course" ALTER COLUMN "locationId" SET NOT NULL;

-- 4. Trainer: same.
ALTER TABLE "Trainer" ADD COLUMN "locationId" TEXT;

UPDATE "Trainer" t
SET "locationId" = l."id"
FROM "Location" l
WHERE l."name" = t."location";

ALTER TABLE "Trainer" ALTER COLUMN "locationId" SET NOT NULL;

-- 5. Old string columns and their indexes are now redundant.
DROP INDEX "Course_location_date_idx";
DROP INDEX "Trainer_location_idx";

ALTER TABLE "Course" DROP COLUMN "location";
ALTER TABLE "Trainer" DROP COLUMN "location";

-- 6. Indexes on the new column, mirroring the ones dropped above.
CREATE INDEX "Course_locationId_date_idx" ON "Course"("locationId", "date");
CREATE INDEX "Trainer_locationId_idx" ON "Trainer"("locationId");

-- 7. Foreign keys. RESTRICT: deleting a location still in use must fail loudly
-- rather than orphan courses or silently retarget them.
ALTER TABLE "Course" ADD CONSTRAINT "Course_locationId_fkey"
    FOREIGN KEY ("locationId") REFERENCES "Location"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Trainer" ADD CONSTRAINT "Trainer_locationId_fkey"
    FOREIGN KEY ("locationId") REFERENCES "Location"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
